#!/usr/bin/env bash

# Go to sites-enabled folder for Nginx
cd /etc/nginx/sites-enabled/ || exit;

# Check if the symbolic link already exists
if [ -L default ]; then
    # If it exists, remove it
    rm default
fi

# Create symbolic link to the default file in sites-available
ln -s /etc/nginx/sites-available/default default

# Restart Nginx
service nginx restart
